# Generated by Django 4.0.3 on 2022-10-25 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_serviceappointment_is_vip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ('name', 'employee_number', 'id')},
        ),
    ]
