# Generated by Django 4.0.3 on 2022-10-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_technician_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ('id', 'employee_number', 'name')},
        ),
    ]
