# Generated by Django 4.0.3 on 2022-10-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_technician_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='date_time',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
